config/app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [#path('registro/estudiante', views.registro_estudiante, name='registro_estudiante'),
               #path('registro/adultoM', views.registro_adultoM, name='registro_adultoM'),
               path('', views.home, name='home'),
               path('usuarios/registro/', views.registro, name="registro"),
               path('usuarios/login/', views.login_view, name="login"),
               path('usuarios/comuna/', views.comuna, name = 'comuna'),
               path('usuarios/campus/', views.campus, name = 'campus'),
               path('usuarios/registro/seleccion/', views.seleccion, name = 'seleccion'),
               path('usuarios/logout', views.logout_view, name='logout'),
               ]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('funciones.urls')),
]

config/funciones/urls.py
from django.urls import path
from . import views
from .pdfcreate import crear_pdf #pdfcreate

urlpatterns = [path('calendario/', views.calendario, name="calendario"),
               path('guardar_fechas/', views.guardar_fechas, name="guardar_fechas"),
               path('borrar_fechas/', views.borrar_fechas, name="borrar_fecha"),
               path('publicar/', views.publicar, name="publicar"),
               path('editar_fechas/', views.editar_fechas, name='editar_fechas'),
               path('perfil/perfil_estudiante/', views.perfil_estudiante, name='perfil_estudiante'),
               path('fechas/', views.fechas_usuario, name='fechas_usuario'),
               path('adulto_mayor/', views.elegir, name='elegir'),
               path('agendar_citas/<str:estudiante_id>', views.agendar_citas, name='agendar_citas'),
               path('citas/', views.mis_citas, name='mis_citas'),
               path('certificado/', views.certificados, name='certificados'),
               path('certificado/pdf/', views.crear_pdf, name='crear_pdf'),
               ]

config/app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Area(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Comuna(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Usuarios(AbstractUser):
    rut = models.CharField(max_length=12, primary_key=True)
    TIPOS = [("ESTUDIANTE","Estudiante"),
    ("ADULTO_MAYOR","Adulto Mayor")]   
    tipo = models.CharField(max_length=20, choices=TIPOS)
    SEDES = [("SANJO","Campus San Joaquin"),
    ("VITA","Campus Vitacura")]
    campus =  models.CharField(max_length=20, choices=SEDES)
    comuna = models.ForeignKey(Comuna, on_delete=models.SET_NULL, null=True, blank=True)
    areas = models.ManyToManyField(Area, blank=True)

    def es_estudiante(self):
        return self.tipo == "ESTUDIANTE"
    
    def es_adulto_mayor(self):
        return self.tipo == "ADULTO_MAYOR"

    def vita(self):
        return self.campus == "VITA"
    
    def sanjo(self):
        return self.campus == "SANJO"

config/funciones/models.py
from django.db import models
from app.models import Usuarios
from django.utils import timezone

# Create your models here.

class FechasDisponibles(models.Model):
    #nombre_persona = models.CharField(max_length=100)
    usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE, null=True, blank=True)
    fecha = models.DateField()
    disponible = models.BooleanField(default=True)
    hora = models.TimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.usuario} - {self.fecha} {self.hora}"
    

class Publi(models.Model):
    usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE, null=True, blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    titulo = models.TextField(max_length=50)
    descripcion = models.TextField(max_length=200)
    
    def __str__(self):
        return f"{self.titulo} {(self.usuario)}"
    
    def tag_area(self):
        return self.usuario.areas.all()
    
    def tag_comuna(self):
        return self.usuario.comuna.nombre

class Cita(models.Model):
    estudiante = models.ForeignKey(Usuarios, on_delete=models.CASCADE, related_name="matches_recibidos")
    adulto_mayor = models.ForeignKey(Usuarios, on_delete=models.CASCADE, related_name="matches_realizados")
    fecha = models.ForeignKey(FechasDisponibles, on_delete=models.CASCADE)
    creado = models.DateTimeField(auto_now_add=True)

    def esta_completada(self):
        return self.fecha.fecha < timezone.now().date()




'''
por implementar en el push
class Cita():
    estudiante = models.ForeignKey(
    Usuarios,
    on_delete=models.CASCADE,
    limit_choices_to={"es_estudiante": True},
    )
    adultoM = models.ForeignKey(
    Usuarios,
    on_delete=models.CASCADE,
    limit_choices_to={"es_adulto_mayor": True},
    )
    fechas = models.DateField()
    #def completo
    #def incompleto
'''

config/funciones/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
'''
class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        fields = ['tipo','rut','username','email', 'password']
'''

class PubliForm(forms.ModelForm):
    class Meta:
        model = Publi
        fields = ['titulo', 'descripcion']
        labels = {
            'titulo': 'Título de la publicación',
            'descripcion': 'Contenido'
        }
        widgets= {
            'titulo': forms.TextInput(attrs={'class':'form-control','placeholder':'Escribe un titulo'}),
            'descripcion':forms.Textarea(attrs={'class':'form-control','rows':5})
        }

config/funciones/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from datetime import date, timedelta, datetime
from .models import FechasDisponibles, Publi
from django.views.decorators.csrf import csrf_exempt
from app.models import Usuarios, Area
from .forms import *
from django.contrib.auth.decorators import login_required
from app.forms import *
from app.models import *
from .pdfcreate import crear_pdf #pdfcreate
from django.utils import timezone
from django.shortcuts import render, redirect
from django.utils import timezone
from funciones.models import Cita

# Create your views here.

def calendario(request):
    # Obtener mes actual
    hoy = date.today() #fecha actual YYYY-MM-DD
    primer_dia = hoy.replace(day=1) #primer día del mes actual
    ultimo_dia = (primer_dia.replace(month=hoy.month % 12 + 1, day=1) - timedelta(days=1)) #último día del mes actual
    
    # Generar lista de días del mes
    dias = [primer_dia + timedelta(days=i) for i in range((ultimo_dia - primer_dia).days + 1)]

    # Obtener eventos del mes
    eventos = FechasDisponibles.objects.filter(fecha__month=hoy.month)

    # Crear diccionario con días y eventos
    calendario = []
    for dia in dias:
        eventos_dia = [e for e in eventos if e.fecha == dia]
        calendario.append({"fecha": dia, "eventos": eventos_dia})

    return render(request, "calendario.html", {"calendario": calendario, "mes": hoy.strftime("%B")})


#@csrf_exempt
def guardar_fechas(request):
    if request.method == "POST":
        fecha = request.POST.get('fecha')
        if fecha:
            fecha_obj = datetime.strptime(fecha, '%Y-%m-%d').date()
            FechasDisponibles.objects.get_or_create(usuario=request.user, fecha=fecha_obj)
            return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'error'})

#@csrf_exempt
def borrar_fechas(request):
    if request.method == "POST":
        fecha = request.POST.get('fecha')
        if fecha:
            fecha_obj = datetime.strptime(fecha, '%Y-%m-%d').date()
            FechasDisponibles.objects.filter(usuario=request.user, fecha=fecha_obj).delete()
            return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'error'})

@login_required
def publicar(request):
    usuario = request.user
    if not usuario.es_estudiante():
        return render(request, 'no_autorizado.html')
    
    if request.method=='POST':
        comuna_form = ComunaForm(request.POST, instance=usuario)
        campus_form = CampusForm(request.POST, instance=usuario)
        seleccion_form = SeleccionForm(request.POST)
        publi_form = PubliForm(request.POST)
        if publi_form.is_valid() and seleccion_form.is_valid() and comuna_form.is_valid() and campus_form.is_valid():
            Publi.objects.filter(usuario=request.user).delete() #borrar el post anterior
            publi = publi_form.save(commit=False)
            publi.usuario = usuario
            publi.save()
            comuna_form.save()
            campus_form.save()
            usuario.areas.set(seleccion_form.cleaned_data['areas'])
            return redirect ('perfil_estudiante') # perfil estudiantes
    else:
        publi_form = PubliForm(initial={'titulo':usuario.username})
        comuna_form = ComunaForm(instance=usuario)
        campus_form = CampusForm(instance=usuario)
        seleccion_form = SeleccionForm(initial={'areas':usuario.areas.all()})
    return render(request, 'publicar.html', {"publi_form": publi_form,
        "comuna_form": comuna_form,
        "seleccion_form": seleccion_form,
        "campus_form": campus_form,})

@login_required
def editar_fechas(request):
    usuario = request.user
    if not usuario.es_estudiante():
        return render(request, "no_autorizado.html")
    return render(request, "perfil/editar_fechas.html")

def fechas_usuario(request):
    usuario = request.user
    fechas = FechasDisponibles.objects.filter(usuario=usuario)
    eventos = []
    for fecha in fechas:
        if fecha.disponible:
            eventos.append({"title": "Disponible", "start": fecha.fecha.isoformat(), "allDay": True})
        else:
            eventos.append({"title": "Agendado", "start": fecha.fecha.isoformat(), "allDay": True, "backgroundColor": "red"})

    return JsonResponse(eventos, safe=False)


@login_required

def perfil_estudiante(request):
    usuario = request.user
    if not usuario.es_estudiante():
        return render(request, "no_autorizado.html")
    publi = Publi.objects.filter(usuario=usuario).first()
    fechas = FechasDisponibles.objects.filter(usuario=usuario).order_by("fecha")
    citas = Cita.objects.filter(estudiante=usuario).select_related("adulto_mayor", "fecha")

    #Contar cuantas citas ya fueron completadas
    total_citas_cumplidas = sum(1 for cita in citas if cita.fecha.fecha < timezone.now().date())
    tiene_certificado = total_citas_cumplidas >= 8
    tipo = "adulto" if usuario.es_adulto_mayor() else "estudiante"
    
    return render(request, "perfil/perfil_estudiante.html", {
        "publi": publi,
        "fechas": fechas,
        "usuario": usuario,
        "citas": citas,
        "tipo":tipo,
        "tiene_certificado": tiene_certificado,
        })

#función para que muestre los perfiles de los estudiantes a los adultos mayores
#filtro por áreas y comuna
@login_required
def elegir(request):
    comuna_adultoM = request.user.comuna
    areas_adultoM = [area.nombre for area in request.user.areas.all()]
    estudiantes = Usuarios.objects.filter(tipo="ESTUDIANTE")
    lista = []
    for estudiante in estudiantes:
        voluntario = Publi.objects.get(usuario=estudiante)
        if estudiante.comuna == comuna_adultoM:
            areas_estudiante = [area.nombre for area in estudiante.areas.all()]
            for area in areas_adultoM:
                if area in areas_estudiante and [estudiante, voluntario, areas_estudiante] not in lista:
                    lista.append([estudiante, voluntario, areas_estudiante])
    tipo = "adulto" if request.user.es_adulto_mayor() else "estudiante"
    return render(request, "elegir.html", {"lista":lista,"tipo":tipo})

@login_required
def agendar_citas(request, estudiante_id):
    adultoM = request.user
    if not adultoM.es_adulto_mayor():
        return render(request, "no_autorizado.html")

    estudiante = get_object_or_404(Usuarios, rut=estudiante_id)
    publi = Publi.objects.filter(usuario=estudiante).first()
    email = estudiante.email
    fechas = FechasDisponibles.objects.filter(usuario=estudiante).order_by("fecha")
    if request.method == "POST":
        fecha_id = request.POST.get("fecha_id")
        fecha = get_object_or_404(FechasDisponibles, id=fecha_id, usuario=estudiante)
        if fecha.disponible:
            fecha.disponible = False
            fecha.save()
            '''
            Cita.objects.update_or_create(
                estudiante=estudiante,
                adulto_mayor=adultoM,
                defaults={"fecha": fecha, "email":email}
            )
            '''
            Cita.objects.update_or_create(
                estudiante = estudiante, 
                adulto_mayor = adultoM,
                fecha  = fecha
            )
            return redirect("mis_citas")
    tipo = "adulto" if request.user.es_adulto_mayor() else "estudiante"
    return render(request, "agendar_citas.html", {
        "estudiante": estudiante,
        "publi": publi,
        "fechas": fechas,
        "tipo":tipo,
    })

@login_required
def mis_citas(request):
    usuario = request.user
    if usuario.es_adulto_mayor():
        citas = Cita.objects.filter(adulto_mayor=usuario).select_related("estudiante", "fecha")
        return render(request, "perfil/ver_citas.html", {"citas": citas})
    elif usuario.es_estudiante():
        citas = Cita.objects.filter(estudiante=usuario).select_related("adulto_mayor", "fecha")
        publi = Publi.objects.filter(usuario=usuario).first()
        fechas = FechasDisponibles.objects.filter(usuario=usuario).order_by("fecha")
        return render(request, "perfil/perfil_estudiante.html", {
            "usuario": usuario,
            "publi": publi,
            "fechas": fechas,
            "citas": citas
        })
    tipo = "adulto" if request.user.es_adulto_mayor() else "estudiante"
    return render(request, "no_autorizado.html",{"tipo":tipo,})





'''
#muestra calendario para agendar el día y la razón de la cita, opción de imprimir comprobante de cita
#envíar notificación al estudiante
def agendar_citas(request):
    adultoM = request.user
    if adultoM.es_estudiante():
        return render(request, "no_autorizado.html")
    return render(request, "agendar_citas.html")


def cita_calendario(request):
    estudiante = get_object_or_404(Usuarios, rut.estudiante_id, tipo="ESTUDIANTE")
    publi = Publi.objects.filter(usuario=estudiante)
    fechas = FechasDisponibles.objects.filter(usuario=estudiante).order_by("fecha")
    if request.method == "POST":
        fecha_id = request.POST.get("fecha_id")
        fecha = get_object_or_404(FechasDisponibles, id=fecha_id, usuario=estudiante)
        Cita.objects.update_or_create(
            voluntario = estudiante
            adultoM = request.user)
            defaults = {"fecha":fecha}
        return redirect("cita_confirmada") #extiende el html de ver perfil
    return render(request, "agendar_citas.html",{"estudiante":estudiante,"publi":publi,"fechas":fechas})
'''

#muestra las citas que tienen agendadas tanto los adultos mayores como los estudiantes
def ver_citas(request):
    #...
    return render(request, "perfil/ver_citas.html")

#cuando se cumplan cierta cantidad de citas el estudiante puede imprimir un certificado
def certificados(request):
    usuario = request.user

    #Verificar que el usuario esté autenticado
    if not usuario.is_authenticated:
        return redirect('login')
    #Obtener todas las citas del usuario

config/funciones/templates/perfil/certificados.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estado del certificado</title>
</head>
<body style="text-align: center; font-family: Helvetica, Arial, sans-serif; margin-top: 50px;">

    <h1>Estado del certificado</h1>
    
    {% if tiene_certificado %}
        <p style="color: green; font-size: 18px;">
            ¡Felicidades! Has completado tus {{total_citas}} citas asignadas 🎉
        </p>
        <a href="{% url 'crear_pdf' %}" target="_blank" class="btn btn-success"
            style="padding: 10px 20px; background-color: #28a745; color: white; border-radius: 5px; text-decoration: none;">
            📄 Descargar Certificado en PDF
        </a>
    {% else %}
        <p style="color: red; font-size: 16px;">
            Aún no cumples con las 8 citas necesarias para obtener tu certificado.
        </p>
        <p style="font-size: 14px;">
            Llevas {{total_citas}} de 8 citas completadas.
        </p>
    {% endif %}
</body>
</html>

config/funciones/templates/perfil/editar_fechas.html
{% extends "index.html" %}
{% block content %}
<div class="container mt-4">
    <h2 class="form-title">Edita tus fechas disponibles</h2>

    <div id="calendar" style="max-width: 1100px; margin: 0 auto;"></div>

    <div class="mt-4 text-center">
        <a href="{% url 'perfil_estudiante' %}" class="btn btn-secondary me-2">Guardar cambios</a>
        <br>
        <a href="{% url 'publicar' %}" class="btn btn-primary">Editar perfil</a>
        <br>
    </div>
</div>

<!-- FullCalendar CSS & JS -->
<link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/index.global.min.js"></script>

<script>
const csrftoken = '{{ csrf_token }}';

document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth',
        locale: 'es',
        events: '/fechas/',

        // Añadir más
        dateClick: function(info) {
            var fecha = info.dateStr;
            var existe = calendar.getEvents().find(ev => ev.startStr === fecha);

            if (!existe) {
                calendar.addEvent({
                    title: "Disponible",
                    start: fecha,
                    allDay: true
                });

                fetch('/guardar_fechas/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'X-CSRFToken': csrftoken
                    },
                    body: 'fecha=' + encodeURIComponent(fecha)
                });
            }
        },

        // quitar
        eventClick: function(info) {
            var fecha = info.event.startStr;
            var eventExistente = calendar.getEvents().find(ev => ev.startStr === fecha);

            if (eventExistente) {
                eventExistente.remove();

                fetch('/borrar_fechas/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'X-CSRFToken': csrftoken
                    },
                    body: 'fecha=' + encodeURIComponent(fecha)
                });
            }
        }
    });

    calendar.render();
});
</script>
{% endblock %}

config/funciones/templates/perfil/perfil_estudiante.html
{% extends "index.html" %}

{% block content %}
<div class="container mt-4">
    <h1 class="form-title">Tu perfil</h1>
    <div class="perfil-p1">
        <!-- Publicación actual -->
        <div class="card mt-4 tu-perfil">
            
            <div class="card-body">
                {% if publi %}
                    <h1 class="card-title">{{ publi.titulo }}</h1>
                    <div class="card-header">Descripción:</div>
                    <h4 class="card-text">{{ publi.descripcion }}</h4>

                    <a href="{% url 'publicar' %}" class="btn btn-outline-primary mt-2">Editar perfil</a>
                {% else %}
                    <p class="no-has">* No has creado tu perfil aún.</p>
                    <a href="{% url 'publicar' %}" class="btn btn-primary">Crear perfil</a>
                {% endif %}
            </div>
            <br>
            <div class="perfil-p2">
                <!-- Áreas seleccionadas -->
                {% if usuario.areas.all %}
                <div class="card mt-4">
                    <div class="card-header">Áreas seleccionadas:</div>
                    <div class="card-body">
                        {% if usuario.areas.all %}
                            <ul class="list-group">
                                {% for area in usuario.areas.all %}
                                    <li class="list-group-item">{{ area.nombre }}</li>
                        {% endfor %}
                            </ul>
                        {% else %}
                            <p class="no-has">* No has seleccionado áreas aún.</p>
                        {% endif %}
                    </div>
                </div>
                {% endif %}

                <!-- Comuna seleccionada -->
                <div class="card mt-4">
                    <div class="card-header">Comuna seleccionada</div>
                    <div class="card-body">
                        {% if usuario.comuna %}
                            <ul class="list-group">
                                <li class="list-group-item">{{ usuario.comuna.nombre }}</li>
                            </ul>
                        {% else %}
                            <p class="no-has">* No has seleccionado comuna aún.</p>
                        {% endif %}
                    </div>
                </div>

                <!-- Campus -->
                <div class="card mt-4">
                    <div class="card-header">Campus</div>
                    <div class="card-body">
                        {% if usuario.campus %}
                            <ul class="list-group">
                                <li class="list-group-item">{{ usuario.get_campus_display }}</li>
                            </ul>
                        {% else %}
                            <p class="no-has">* No has seleccionado campus aún.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        
        <div class="card mt-4 tus-citas">
            <!--Ver citas-->
            <div class="card-header">Citas agendadas</div>
            <div class="card-body">
                {% if citas %}
                <ul class="list-group">
                    {% for cita in citas %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div>
                            <strong>Adulto mayor:</strong> {{ cita.adulto_mayor.first_name }} {{ cita.adulto_mayor.last_name }}<br>
                            <strong>Fecha:</strong> {{ cita.fecha.fecha }}
                        </div>
                        <span class="badge {% if cita.esta_completada %}bg-success{% else %}bg-warning text-dark{% endif %}">
                            {% if cita.esta_completada %}Completada{% else %}Pendiente{% endif %}
                        </span>
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                <p>No tienes citas agendadas aún.</p>
                {% endif %}
            </div>
            
            <!--Boton del certificado-->
            <div class="text-center mt-3 mb-4">
                {% if tiene_certificado %}
                    <a href="{% url 'certificados' %}" 
                        class="btn btn-success"
                        style="
                            padding: 10px 20px;
                            background-color: rgb(73, 91, 255);
                            color: white;
                            border-radius: 5px;
                            text-decoration: none;
                            font-weight: bold;
                        ">
                        🎓 Ver estado del certificado
                    </a>
                    <br>
                {% else %}
                    <p style="color: gray; margin-top: 15px;">
                        Aún no cumples con las 8 citas necesarias para obtener tu certificado.
                    </p>
                {% endif %}
            </div>

            <!--Ver fechas-->
            <div class="card mb-4">
                <div class="card-header">Fechas disponibles</div>
                <div class="card-body">
                    {% if fechas %}
                        <ul>
                            {% for fecha in fechas %}
                                <li>{{ fecha.fecha|date:"l j F Y" }}</li>
                            {% endfor %}
                        </ul>
                        <a href="{% url 'editar_fechas' %}" class="btn btn-outline-secondary">Editar fechas</a>
                    {% else %}
                        <p class="no-has">* No has seleccionado fechas aún.</p>
                        <a href="{% url 'editar_fechas' %}" class="btn btn-secondary">Seleccionar fechas</a>
                    {% endif %}
                </div>
            </div>
        </div>
        
    </div>
    
</div>

{% endblock %}

config/funciones/templates/perfil/ver_citas.html
{% extends "index.html" %}
{% block content %}
<div class="container mt-4">
    <h2>Mis citas agendadas</h2>

    {% if citas %}
    <ul class="list-group">
        {% for cita in citas %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <div class="card mt-4 tu-perfil">
                <div>
                    <h2 class="card-title"><b>{{ cita.estudiante.first_name }} {{ cita.estudiante.last_name }}</b></h2>
                    <strong>Campus del Estudiante:</strong> {{ cita.estudiante.get_campus_display }}<br>
                    <strong>Fecha:</strong> {{ cita.fecha.fecha }}<br>
                    <strong>La comunicación es esencial!</strong><br>
                    <strong>Contactate mediante:</strong> {{ cita.estudiante.email }}
                </div>
                <span class="badge {% if cita.esta_completada %}bg-success{% else %}bg-warning text-dark{% endif %}">
                    <strong>Estado:</strong>
                    {% if cita.esta_completada %}Completada{% else %}Pendiente{% endif %}
                </span>
            </div>
        </li>
        <br>
        {% endfor %}
    </ul>
    {% else %}
    <p>No tienes citas agendadas aún.</p>
    {% endif %}
</div>

<div class="mt-4">
        <a href="{% url 'elegir' %}" class="button">Volver al listado</a>
</div>
{% endblock %}